models/Entradas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "entradas".
 *
 * @property int $cod
 * @property int|null $numero_entrada
 * @property int|null $cod_festivales
 *
 * @property Compran[] $comprans
 * @property Clientes[] $codClientes
 * @property Festivales[] $codFestivales
 * @property Festivales $codFestivales0
 */
class Entradas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'entradas';
    }
    
   

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cod', 'numero_entrada', 'cod_festivales'], 'required'],
            [['cod', 'numero_entrada', 'cod_festivales'], 'integer'],
            [['cod'], 'unique'],
            [['cod_festivales'], 'exist', 'skipOnError' => true, 'targetClass' => Festivales::className(), 'targetAttribute' => ['cod_festivales' => 'cod']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cod' => 'Cod',
            'numero_entrada' => 'Numero de Entrada',
            'cod_festivales' => 'Código del Festival',
            'Nombres_Festivales' => 'Nombre del Festival',
        ];
    }

    /**
     * Gets query for [[Comprans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComprans()
    {
        return $this->hasMany(Compran::className(), ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodClientes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodClientes()
    {
        return $this->hasMany(Clientes::className(), ['cod' => 'cod_clientes'])->viaTable('compran', ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodFestivales]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodFestivales()
    {
        return $this->hasMany(Festivales::className(), ['cod' => 'cod_festivales'])->viaTable('compran', ['cod_entradas' => 'cod']);
    }

    /**
     * Gets query for [[CodFestivales0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodFestivales0()
    {
        return $this->hasOne(Festivales::className(), ['cod' => 'cod_festivales']);
    }
}

controllers/EntradasController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Entradas;
use app\models\EntradasSearch;
use kartik\mpdf\Pdf;




/**
 * EntradasController implements the CRUD actions for Entradas model.
 */
class EntradasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Entradas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EntradasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);

    }

    /**
     * Displays a single Entradas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Entradas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Entradas();
        $nombre = "Crear Entrada";

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('create', [
            'model' => $model,
            'nombre' => $nombre,
        ]);
    }

    /**
     * Updates an existing Entradas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $nombre = "Actualizar";
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cod]);
        }

        return $this->render('update', [
            'model' => $model,
            'nombre' => $nombre,
        ]);
    }

    /**
     * Deletes an existing Entradas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionEnt()
    {
        $aforo = array(
            "medusa" => (new \yii\db\Query())->from('entradas')->where(['cod_festivales' => '109'])->count('numero_entrada'),
            "riverland" => (new \yii\db\Query())->from('entradas')->where(['cod_festivales' => '9'])->count('numero_entrada'),
            "sunblast" => (new \yii\db\Query())->from('entradas')->where(['cod_festivales' => '533'])->count('numero_entrada'),
            "arenal" => (new \yii\db\Query())->from('entradas')->where(['cod_festivales' => '1000'])->count('numero_entrada'),
            
        );

        $ventas = array(
            "medusa" => (new \yii\db\Query())->from('compran')->where(['cod_festivales' => '109'])->count('cod_entradas') * 100,
            "riverland" => (new \yii\db\Query())->from('compran')->where(['cod_festivales' => '9'])->count('cod_entradas') * 100,
            "sunblast" => (new \yii\db\Query())->from('compran')->where(['cod_festivales' => '533'])->count('cod_entradas') * 100,
            "arenal" => (new \yii\db\Query())->from('compran')->where(['cod_festivales' => '1000'])->count('cod_entradas') * 100,
            
        );

        $procentajes = array(
            "medusa" => $ventas['medusa']/$aforo['medusa'],
            "riverland" => $ventas['riverland']/$aforo['riverland'],
            "sunblast" => $ventas['sunblast']/$aforo['sunblast'],
            "arenal" => $ventas['arenal']/$aforo['arenal'],
            
            
        );
        return $this->render('entradas', 
        [
            'aforo' => $aforo,
            'procentaje' => $procentajes,    
        ]);
    }

    public function actionFilter()
    {
        $model = new EntradasSearch();
        return $this->render('_search', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Entradas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Entradas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Entradas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    

    public function actionImprimir (){
        // Puedes vaciar todo el contenido html en una variable
        $dataProvider = new ActiveDataProvider([
            'query' => Entradas::find(),
        ]);

        $content = $this->renderPartial('/layouts/datos_entradas',
        [
          'dataProvider'=>$dataProvider,        
          
          ]); 

        // Debes crear un objeto el cual vas a usar para generar el pdf.
        // El parámetro 'content' puede ser sustituido con una vista, yo te recomiendo usar la función: $this->renderPartial('_ruta_de_tu_vista')
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
            //'content' => $this->renderPartial('privacy'),
            
            'destination' => Pdf::DEST_DOWNLOAD,
            
                // portrait orientation
                //'orientation' => Pdf::ORIENT_LANDSCAPE,        
                // 'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        ]);

        $file_name = 'Datos_Entradas.pdf';                                                            

        $pdf->content = $content;
        $pdf->filename = $file_name;
        //echo "Descomenta para ver html:" . $content;

        return $pdf->render();          
    }

}



views/entradas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Festivales;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container-fluid" style="margin-top: 65px; padding-top: 30px; padding-bottom: 30px;">
    <div class="container bg-condiciones">
        <div class="entradas-form">

            <h1><?= $titulo ?></h1>

            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'numero_entrada')->textInput() ?>

            <?= $form->field($model, 'cod_festivales')->dropDownList(
                    ArrayHelper::map(Festivales::find()->all(),'cod','nombre'),
                        ['prompt' => 'Selecciona un festival'])->label('Nombre del Festival') ?>

            <div class="form-group">
            <div class="form-group">
                <?php if (Yii::$app->user->isGuest) { ?>
                    <?= Html::submitButton('Registrarme', ['class' => 'btn btn-warning']) ?>

                <?php } else { ?>
                    <?= Html::submitButton($nombre, ['class' => 'btn btn-warning']) ?>
                <?php } ?>
            </div>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/entradas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EntradasSearch */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Filtro de Entradas';
?>
<div class="container-fluid" style="margin-top: 65px; padding-top: 30px; padding-bottom: 30px;">
    <div class="container bg-condiciones">
        <div class="entradas-search">

            <h1>Filtro de Entradas</h1>

            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>

            <?= $form->field($model, 'Nombres_Festivales' ) ?>

            <div class="form-group text-center">
                <?= Html::submitButton('Buscar', ['class' => 'btn btn-warning']) ?>
                <?= Html::resetButton('Limpiar', ['class' => 'btn btn-outline-secondary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/entradas/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = 'Crear Nueva Entrada';
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-create">

    <?php $titulo =  Html::encode($this->title) ?>

    <?= $this->render('_form', [
        'model' => $model,
        'titulo' => $titulo,
        'nombre' => $nombre,
    ]) ?>

</div>

views/entradas/entradas.php
<?php
/* @var $this yii\web\View */

use app\models\Entradas;
use app\models\Festivales;
use yii\helpers\Html;


$this->title = 'Entradas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid" style="margin-top: 65px; padding-top: 30px; padding-bottom: 30px;">
    <div class="container bg-condiciones">
        <div class="site-entradas">
            <div class="col-md-12">
                <h1>Festivales Disponibles</h1>
                <?php if ($procentaje['arenal'] != 100) { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Arenal</h2>
                                <p><?= round($procentaje['arenal'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Arenal</h2>
                                <p><?= round($procentaje['arenal'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/entradas/ent'], ['class' => 'btn btn-warning', 'disabled' => true]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="col-md-2 mt"></div>
                <?php if ($procentaje['riverland'] != 100) { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Riverland</h2>
                                <p><?= round($procentaje['riverland'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Riverland</h2>
                                <p><?= round($procentaje['riverland'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/entradas/ent'], ['class' => 'btn btn-warning', 'disabled' => true]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>

            <div class="col-md-12 mt">
                <?php if ($procentaje['sunblast'] != 100) { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Sunblast</h2>
                                <p><?= round($procentaje['sunblast'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Sunblast</h2>
                                <p><?= round($procentaje['sunblast'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/entradas/ent'], ['class' => 'btn btn-warning', 'disabled' => true]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="col-md-2 mt"></div>
                <?php if ($procentaje['medusa'] != 100) { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Medusa</h2>
                                <p><?= round($procentaje['medusa'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/compran/create'], ['class' => 'btn btn-warning']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="col-sm-5 text-center bordes">
                        <div class="thumbnail">
                            <div class="caption">
                                <h2>Medusa</h2>
                                <p><?= round($procentaje['medusa'], 1) ?>%</p>
                                <div>
                                    <?= Html::a('Comprar', ['/entradas/ent'], ['class' => 'btn btn-warning', 'disabled' => true]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php }  ?>
            </div>
        </div>
    </div>
</div>

views/entradas/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Entradas';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="container-fluid" style="margin-top: 65px; padding-top: 30px; padding-bottom: 30px;">
    <div class="container">
        <div class="entradas-index">

        <?php
            $gridColumns = [
                'numero_entrada',
                'Festival',
            ];

            // Renders a export dropdown menu

            ?>

            
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                
                'columns' => [
                    'numero_entrada',
                    [
                        'attribute' => 'Nombres_Festivales',
                        'value' => 'codFestivales0.nombre'
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
                'toolbar' => [
                    [
                        'content' => ExportMenu::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => $gridColumns,
                            'clearBuffers' => true, //optional
                            'exportConfig' => [
                                ExportMenu::FORMAT_TEXT => false,
                                ExportMenu::FORMAT_HTML => false,
                                ExportMenu::FORMAT_EXCEL => false,
                                ExportMenu::FORMAT_CSV => false,
                                ExportMenu::FORMAT_PDF => false,
                                ExportMenu::FORMAT_EXCEL_X => false,
                            ],
                            'filename' => 'Datos_Clientes' . ' ' . date('d-m-y')
                        ]),

                    ],



                ],
                'panel' => [
                    'heading' => '<h3 class="panel-title"><i class="fas fa-ticket-alt"></i> ' . $this->title . '</h3>',
                    'type' => 'warning',
                    'before' => Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], [
                        'type' => 'button',
                        'title' => 'Crear Entrada',
                        'class' => 'btn btn-warning'
                    ]),
                    

                ],

            ]); ?>
        </div>
    </div>
</div>

views/entradas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = 'Entrada: ' . $model->numero_entrada;
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cod, 'url' => ['view', 'id' => $model->cod]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="entradas-update">

    <?php $titulo = "Actualizar Entrada:" . " ". Html::encode($model->numero_entrada) ?>

    <?= $this->render('_form', [
        'model' => $model,
        'titulo' => $titulo,
        'nombre' => $nombre,
    ]) ?>

</div>

views/entradas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

$this->title = "Entrada " . $model->numero_entrada;
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="container-fluid" style="margin-top: 65px; padding-top: 30px; padding-bottom: 30px;">
    <div class="container bg-condiciones">
        <div class="entradas-view">

            <h1>Número de Entrada: <?= Html::encode($model->numero_entrada) ?></h1>

            <p>
                <?= Html::a('Actualización', ['update', 'id' => $model->cod], ['class' => 'btn btn-warning']) ?>
                <?= Html::a('Borrar', ['delete', 'id' => $model->cod], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => '¿Estas seguro que deseas borrar este registro?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'cod',
                    'numero_entrada',
                    [
                        'label' => 'Nombre del  Festival',
                        'value' => $model->codFestivales0->nombre,

                    ],
                ],
            ]) ?>

        </div>
    </div>
</div>